# Generated by Django 2.2.6 on 2019-10-31 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuskar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='hashval',
            field=models.CharField(default='adssasdasd', max_length=255),
        ),
    ]
