# Generated by Django 2.2.6 on 2019-10-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuskar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='stopped_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='students_present',
            field=models.ManyToManyField(blank=True, to='fuskar.Student'),
        ),
    ]
