# Generated by Django 2.2.6 on 2019-10-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuskar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='registered_students',
            field=models.ManyToManyField(blank=True, to='fuskar.Student'),
        ),
    ]
