# Generated by Django 2.2.6 on 2019-10-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuskar', '0002_auto_20191024_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='stopped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
