# Generated by Django 2.2.6 on 2019-10-31 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuskar', '0002_image_hashval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='hashval',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
