# Generated by Django 2.2.6 on 2019-10-31 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuskar', '0003_auto_20191031_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='hashval',
            field=models.CharField(error_messages={'unique': 'Image is an exact duplicate of an existing imagw'}, max_length=255, unique=True),
        ),
    ]
