# Generated by Django 2.2.6 on 2019-10-27 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuskar', '0004_taskscheduler'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskscheduler',
            name='lecture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fuskar.Lecture'),
        ),
    ]
