# Generated by Django 2.2.6 on 2019-11-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuskar', '0004_auto_20191031_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='hashval',
            field=models.CharField(default=330422010709501753072157267700953382686, error_messages={'unique': 'Image is an exact duplicate of an existing imagw'}, max_length=255, unique=True),
        ),
    ]
