# Generated by Django 2.2.6 on 2019-11-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuskar', '0005_auto_20191102_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capturing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='hashval',
            field=models.CharField(error_messages={'unique': 'Image is an exact duplicate of an existing imagw'}, max_length=255, unique=True),
        ),
    ]
