# Generated by Django 2.2.6 on 2019-11-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuskar', '0006_auto_20191104_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(choices=[('calm', 'calm'), ('anger', 'anger'), ('happiness', 'happiness')], max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='lecture',
            name='emotions',
            field=models.ManyToManyField(blank=True, to='fuskar.Emotion'),
        ),
    ]
